version: "3"

services:
  
  node:
    build: .
    image: node:16
    container_name: jobs
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: pass123456
      MYSQL_HOST: db
      MYSQL_DATABASE: jobs
    depends_on:
      - db
  
  db:
    container_name: jobs_db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123456